//generated by ChatGpt
export function calculateMortgage(
  realEstatePrice: number,
  downPayment: number,
  annualInterestRate: number,
  loanTermYears: number
) {
  // Loan amount
  let loanAmount = realEstatePrice - downPayment;
  // Monthly interest rate
  let monthlyInterestRate = annualInterestRate / 100 / 12;

  // Number of monthly payments
  let numberOfPayments = loanTermYears * 12;

  // Mortgage payment formula: M = P[r(1+r)^n]/[(1+r)^n-1]
  let monthlyPayment =
    (loanAmount *
      (monthlyInterestRate *
        Math.pow(1 + monthlyInterestRate, numberOfPayments))) /
    (Math.pow(1 + monthlyInterestRate, numberOfPayments) - 1);

  return monthlyPayment;
}

// Example usage:
let realEstatePrice = 200000; // Total property price
let downPayment = 40000; // Down payment

let interestRate = 5; // Annual interest rate
let loanTerm = 30; // Loan term in years

let monthlyPayment = calculateMortgage(
  realEstatePrice,
  downPayment,
  interestRate,
  loanTerm
);
console.log('Monthly Mortgage Payment: $' + monthlyPayment);
